name: LoginWit
version: '1.0.0'
main: com.loginwit.LoginWitPlugin
api-version: '1.21'
author: Angel
website: https://github.com/Angel1037/LoginWit

commands:
  login:
    description: Inicia sesión.
    usage: /login <contraseña>

  register:
    description: Registra una cuenta.
    usage: /register <contraseña> <confirmación>

  loginwit:
    description: Comando principal de LoginWit.
    usage: /loginwit

permissions:
  loginwit.admin:
    description: Permite administrar LoginWit.
    default: op
